version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1001:1001
    ports:
      - 80:80
    volumes:
      - /home/${DOCKER_USER}/:/srv
      - /home/${DOCKER_USER}/docker/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
networks:
  default:
    name: tunnel
    external: true