version: "2.1"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /home/${DOCKER_USER}/docker/filebrowser/config:/config
      - /home/${DOCKER_USER}:/srv
      
    ports:
      - 49154:80
    restart: unless-stopped